name: "Test variables"
on: 
  push:

env:
  MY_ENV_VAR: "Hello, World! Workflow"

jobs:
  job1:
    env:
       MY_ENV_VAR: "Hello, World! Job 1"
    runs-on: ubuntu-latest
    steps:
      - name: Print env var
        env:
          MY_ENV_VAR: "Hello, World! Step 1"
        run: echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
