name: My custom action
description: "My custom Action"
inputs:
  entorno:
     description: Entorno a usar
     default: int

runs:
  using: composite
  steps:
    - name: Print env var
      env:
        MY_ENV_VAR: "Hello, World! Step 1"
      shell: bash
      run: 
          | 
          echo "The value of MY_ENV_VAR is $MY_ENV_VAR"       
      
    - name: Entorno ${{inputs.entorno}} 
      shell: bash
      run: 
          |
          echo "This step runs in entorno ${{inputs.entorno}}"