name: "My custom Acton"
description: custom action
    
inputs:    
  entorno:  
     description: "Environment to use"
     default: "int"
runs:
  using: composite
  steps:
    - run:  | 
            echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
      shell: bash
       
    - name: Entorno ${{inputs.entorno}} 
      shell: bash
      run: 
            |
            echo "This step runs in entorno ${{inputs.entorno}} "


        

            