name: "Test variables"
on:   

  workflow_dispatch:
    inputs:    
      entorno:
          type: string
          description: "Environment to use"
          default: "int"

env:
  MY_ENV_VAR: "Hello, World! Workflow"

jobs:
  job1:    
    env:
       MY_ENV_VAR: "Hello, World! Job 1"
    runs-on: ubuntu-latest             
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/action/my-custom-action
        with:
          entorno: ${{inputs.entorno}}


        
