name: "Test custom action"
on:   

  workflow_dispatch:
    inputs:    
      environment:
          type: string
          description: "Environment to use"
          default: "int"

env:
  MY_ENV_VAR: "Hello, World! Workflow"

jobs:
  job1:    
    env:
       MY_ENV_VAR: "Hello, World! Job 1"
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}           
    steps:

      - uses: actions/checkout@v4
      - name: Print env var
        env:
          MY_ENV_VAR: "Hello, World! Step 1"
        run: 
            | 
            echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
            echo "The value of VAR_ROLE es ${{ vars.VAR_ROLE }}"
       
      - name: Select environment
        uses: ./.github/actions/my-custom-action
        with:
          entorno: ${{inputs.environment}}


        

            